# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

In [ ]:
布尔型、浮点型、整数型

1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [42]:
start = 1
sum = 0
while start <100:
    temp = start % 2
    if temp ==1:
        sum = sum + start
    else:
        sum = sum - start
    #print(start)
    #sum = sum + 1
    start += 1
print(sum)

50


1.3  将字符串 s="yoyo" 转换成列表

In [ ]:
s='yoyo'
list(s)

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的
        

In [ ]:
取最后十个结果，范围是1到100中的从2开始，间隔3

2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [ ]:
[column for column in df]
df.columns.values 返回 array
list(df)
df.columns 返回Index,可以通过tolist(),或者list(array)转换为list


DataFrame.T

3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [23]:
import pandas as pd
import numpy as np
import datetime as datetime
import warnings
warnings.filterwarnings('ignore')

In [27]:
import talib as ta
stock_close = pd.read_excel('sz50.xlsx','600036.XSHG',index_col='datetime')['close']
close = np.array(stock_close)
ma_10 = ta.MA(close,timeperiod=10)
print(type(ma_10))
print(ma_10[-5:])

<class 'numpy.ndarray'>
[108.35  108.741 109.176 110.102 111.666]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [ ]:
from datetime import datetime
import pandas as pd
symbol=['600036.XSHG','600050.XSHG','601318.XSHG']
data_dict = {}
for s in symbol:
    data_1 =  pd.read_excel('sz50.xlsx',sheetname=s, index_col='datetime')
PN = pd.Panel(data_1)
print(PN)

3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [ ]:
data_2=np.array(data_1)
print(data_2shape)
print(data_2[:,-20:,1])

3.5 建立一个5*5的矩阵，值从0到24

In [32]:
import numpy as np
arr1 = np.arange(25).reshape(5,5)
print(arr1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
